-------------------------------------------------------
   SELECT
        2                            					 AS step,
        'vaccine records and event post 8th Dec 2020'    AS criteria,
        COUNT(*)                                         AS n_alf,
        SUM(out_any_myo_or_pericarditis IS NOT null)     AS n_event
    FROM
        sailwWMCCV.ccu002_03_cohort_analysis_dose1 ;

SELECT count(DISTINCT NHS_NUMBER_DEID )  FROM   sailwWMCCV.ccu002_03_cohort_analysis_dose1 
WHERE out_any_myo_or_pericarditis IS NOT null;
-------------------------------------------------------
SELECT count(DISTINCT ALF_E ) FROM   sailwWMCCV.ccu002_03_cohort_analysis
WHERE OUT_DOSE1_ANY_MYO_OR_PERICARDITIS IS NOT NULL OR OUT_DOSE2_ANY_MYO_OR_PERICARDITIS IS NOT NULL;

SELECT ALF_E , VACCINATION_DOSE1_DATE ,
	CASE 
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc1, 
	VACCINATION_DOSE2_DATE , 
	CASE 
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc2, 
	OUT_DOSE1_ANY_MYO_OR_PERICARDITIS , OUT_DOSE2_ANY_MYO_OR_PERICARDITIS ,
DAYS(OUT_DOSE1_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE1_DATE) d1_days_diff  ,
DAYS(OUT_DOSE2_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE2_DATE) d2_days_diff
FROM   sailwWMCCV.ccu002_03_cohort_analysis
WHERE OUT_DOSE1_ANY_MYO_OR_PERICARDITIS IS NOT NULL OR OUT_DOSE2_ANY_MYO_OR_PERICARDITIS IS NOT NULL;
-------------------------------------------------------
--dose 1
SELECT * FROM (
SELECT DISTINCT 
	'dose 1' AS vacc,
	vacc1, 
	CASE 
	WHEN d1_days_diff < 0 THEN 'pre expo'
	WHEN d1_days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN d1_days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END AS expo_week, 
	count(DISTINCT ALF_E ) patient_count
FROM (	

	SELECT ALF_E , VACCINATION_DOSE1_DATE ,
	CASE 
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc1, 
	VACCINATION_DOSE2_DATE , 
	CASE 
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc2, 
	OUT_DOSE1_ANY_MYO_OR_PERICARDITIS , OUT_DOSE2_ANY_MYO_OR_PERICARDITIS ,
	DAYS(OUT_DOSE1_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE1_DATE) d1_days_diff  ,
	DAYS(OUT_DOSE2_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE2_DATE) d2_days_diff
	FROM   sailwWMCCV.ccu002_03_cohort_analysis
	WHERE OUT_DOSE1_ANY_MYO_OR_PERICARDITIS IS NOT NULL OR OUT_DOSE2_ANY_MYO_OR_PERICARDITIS IS NOT NULL

)
GROUP BY 
	vacc1,
	CASE 
	WHEN d1_days_diff < 0 THEN 'pre expo'
	WHEN d1_days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN d1_days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END
	
UNION 
--dose 2
SELECT DISTINCT 
	'dose 2' AS vacc,
	vacc2, 
	CASE 
	WHEN d2_days_diff < 0 THEN 'pre expo'
	WHEN d2_days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN d2_days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END AS expo_week, 
	count(DISTINCT ALF_E ) patient_count
FROM (	

	SELECT ALF_E , VACCINATION_DOSE1_DATE ,
	CASE 
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE1_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc1, 
	VACCINATION_DOSE2_DATE , 
	CASE 
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc2, 
	OUT_DOSE1_ANY_MYO_OR_PERICARDITIS , OUT_DOSE2_ANY_MYO_OR_PERICARDITIS ,
	DAYS(OUT_DOSE1_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE1_DATE) d1_days_diff  ,
	DAYS(OUT_DOSE2_ANY_MYO_OR_PERICARDITIS)-DAYS(VACCINATION_DOSE2_DATE) d2_days_diff
	FROM   sailwWMCCV.ccu002_03_cohort_analysis
	WHERE OUT_DOSE1_ANY_MYO_OR_PERICARDITIS IS NOT NULL OR OUT_DOSE2_ANY_MYO_OR_PERICARDITIS IS NOT NULL

)
GROUP BY 
	vacc2,
	CASE 
	WHEN d2_days_diff < 0 THEN 'pre expo'
	WHEN d2_days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN d2_days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END
	

UNION 
---dose2 - pre vacc2
SELECT DISTINCT
	'dose 2' AS vacc, 
	CASE 
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE null END AS vacc1, 
	CASE 
	WHEN days_diff < 0 THEN 'pre expo'
	WHEN days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END AS expo_week, 
	count(DISTINCT NHS_NUMBER_DEID )
FROM 
(	
SELECT NHS_NUMBER_DEID ,VACCINATION_DOSE1_DATE , VACCINATION_DOSE2_DATE ,VACCINATION_DOSE2_PRODUCT ,OUT_ANY_MYO_OR_PERICARDITIS, 
days(OUT_ANY_MYO_OR_PERICARDITIS)-days(VACCINATION_DOSE2_DATE) days_diff
FROM sailwWMCCV.CCU002_03_COHORT_ANALYSIS_DOSE2 ccad
WHERE OUT_ANY_MYO_OR_PERICARDITIS IS NOT NULL 
AND OUT_ANY_MYO_OR_PERICARDITIS BETWEEN VACCINATION_DOSE1_DATE AND VACCINATION_DOSE2_DATE 
AND NHS_NUMBER_DEID IN (SELECT DISTINCT NHS_NUMBER_DEID  FROM   sailwWMCCV.ccu002_03_cohort_analysis_dose1 
					WHERE out_any_myo_or_pericarditis IS NOT null)
)
GROUP BY 
	CASE
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (ASTRAZENECA)' THEN 'AZ'
	WHEN VACCINATION_DOSE2_PRODUCT ='COVID-19 (PFIZER BIONTECH)' THEN 'Pf' ELSE NULL END ,
	CASE 
	WHEN days_diff < 0 THEN 'pre expo'
	WHEN days_diff BETWEEN 0 AND 14 THEN 'week1-2'
	WHEN days_diff BETWEEN 15 AND 161 THEN 'week3-23' ELSE NULL END

)
WHERE expo_week IS NOT NULL 
ORDER BY vacc , vacc1, expo_week;
